### PR TITLE
Follow up on #34

### PR DESCRIPTION
**Pull request by alexsnaps**
Proposition about addressing #34 
 1. Be defensive about the wrong type being passed in 
 1. Update to the `README.md`

If that makes sense, I'll add a test for [the defensive part](https://github.com/Shopify/memcached_store/pull/35/commits/d709c389f4240e4c9a0bd9f1c00548f3c64dae48)

### CODE REVIEW

**Comment by rafaelfranca** [comment]
:+1:

**Comment by wiracocha** [comment]
Is the documentation actually correct? I made the change to a Rails 5.0.3 app following the documentation in this PR:
```Ruby
config.identity_cache_store = :memcached_store, Memcached.new(servers: ['memcached1.foo.com', 'memcached2.foo.com'])
IdentityCache.cache_backend = ActiveSupport::Cache.lookup_store(*Rails.configuration.identity_cache_store)
```

However I'm getting:
```Ruby
/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/memcached-1.8.0/lib/memcached/memcached.rb:209:in `block in set_servers': Servers must be either in the format 'host:port[:weight]' (e.g., 'localhost:11211' or  'localhost:11211:10') for a network server, or a valid path to a Unix domain socket (e.g., /var/run/memcached). (ArgumentError)
```

Checking the parameters to initialize Memcached you should pass the array of servers and the options:
```Ruby
def initialize(servers = nil, opts = {})
  [...]
end
```

If I change the above like this:
```Ruby
identity_cache_options = { support_cas: true, default_ttl: 7.days.seconds.to_i, auto_eject_hosts: false }
config.identity_cache_store = :memcached_store, Memcached.new(['memcached1.foo.com', 'memcached2.foo.com'], identity_cache_options)
```
it works. Also because we are initializing directly Memcached we can't use options like `expires_in`, otherwise I'll get: 
```Ruby
:expires_in is not a valid configuration parameter
```

Am I missing something?

**Comment by alexsnaps** [comment]
Yes, you are correct, `Memcached`'s `#initialize` never supported that `servers:` param, let me address this

**Comment by alexsnaps** [comment]
Trying to reason around the `:expires_in` now... `Memcached::Rails` shouldn't have had support that neither (other than passing it to an actual `#write`).

**Comment by alexsnaps** [comment]
So, on `v1.0.0`, adding a test as:
```
    identity_cache_options = { support_cas: true, expires_in: 7.days.seconds.to_i, auto_eject_hosts: false }
    ActiveSupport::Cache.lookup_store(:memcached_store, Memcached::Rails.new(['memcached1.foo.com', 'memcached2.foo.com'], identity_cache_options))
```
I do get a failure:
```
ArgumentError: :expires_in is not a valid configuration parameter.
    /Users/alexsnaps/.gem/ruby/2.3.3/gems/memcached-1.8.0/lib/memcached/memcached.rb:115:in `block in initialize'
    /Users/alexsnaps/.gem/ruby/2.3.3/gems/memcached-1.8.0/lib/memcached/memcached.rb:113:in `each'
    /Users/alexsnaps/.gem/ruby/2.3.3/gems/memcached-1.8.0/lib/memcached/memcached.rb:113:in `initialize'
    /Users/alexsnaps/.gem/ruby/2.3.3/gems/memcached-1.8.0/lib/memcached/rails.rb:35:in `initialize'
    /Users/alexsnaps/src/github.com/Shopify/memcached_store/test/test_memcached_store.rb:15:in `new'
    /Users/alexsnaps/src/github.com/Shopify/memcached_store/test/test_memcached_store.rb:15:in `test_injecting_memcached'
```

afaict, `:expires_in` never was supported.

**Comment by alexsnaps** [comment]
@wiracocha you confirm my test case above is correct?
Can you point me at what you used to run into this situation to begin with?
I'll make sure downstream dependencies get their doc updated (i.e. IDC afaict)

**Comment by wiracocha** [comment]
Yeah, the test case is correct, the problem here (which is the case that I used to run in this situation) is on IDC documentation which suggests:
```Ruby
config.identity_cache_store = :memcached_store,
  Memcached::Rails.new(servers: ["mem1.server.com"],
    support_cas: true,
    auto_eject_hosts: false,  # avoids more cache consistency issues
    expires_in: 6.hours.to_i, # in case of network errors when sending a delete
  )
```
However, as expected, on a vanilla Rails app that triggers the same `ArgumentError` you are getting. So in my opinion `Memcached.new` must be instantiated by passing the servers array and the [only supported options](https://github.com/arthurnn/memcached/blob/1c659c0d15bcdbd058fff89cc2a696c141011ef4/lib/memcached/memcached.rb#L74) for memcache.

In relation to IDC, in the environments, you can do (correct me if I'm wrong):
```Ruby
identity_cache_options = { support_cas: true, default_ttl: 5.days.seconds.to_i }
config.identity_cache_store = :memcached_store, Memcached.new(['memcached1.foo.com', 'memcached2.foo.com'], identity_cache_options)
```
and then in the initializer:
```Ruby
IdentityCache.cache_backend = ActiveSupport::Cache.lookup_store(*Rails.configuration.identity_cache_store)
```
Or
```Ruby
identity_cache_options = { support_cas: true, expires_in: 5.days.seconds.to_i, compress: true }
config.identity_cache_store = :memcached_store, ['memcached1.foo.com', 'memcached2.foo.com'], identity_cache_options
```
and use the same initializer. 

Both returns `ActiveSupport::Cache::MemcachedStore`, however the first interacts directly with the memcache servers and change their default parameters (for example the `default_ttl` became 518_400); the second one instead leaves most of the default configuration parameters untouched and delegates them to Rails (`default_ttl` remains the initial 604_800).

So the problem seems to me more a documentation inconsistency depending on how you set the `identity_cache_store` and depends if you want to deal directly with the memcache servers (first option) or use the Rails 'way' (second option).

**Pull request merged**
